### ISSUE TITLE
Proposal: default console format

### ISSUE THREAD

**Issue by dm1try** [reprah/grape-raketasks#4]
I like _rails-style_ format for printing routes :)
`"#{description}  #{method} #{:path}"`

That do you think?

**Comment by reprah** [comment]
You mean you like how the rails-style routes are printed horizontally across the whole screen?

I like that too, but there's a reason I didn't do that here. It bugs me when a printed route row is really long and it wraps around my screen. My window is usually broken up into multiple tmux panes, so rows tend to wrap onto the next line, and it's difficult to tell which fields are part of which row.

There's a really long Grape::Route option called `compiled` that I was concerned about.

Is that a concern for you or any other Grape users you know?

**Comment by dm1try** [comment]
Yep, 

> routes are printed horizontally

and just `#{description} #{method} #{:path}`

Honestly, I very rarely use the `rake routes` command and you have compelling reason) Close.
